### ISSUE TITLE
about.html 生成失败

### ISSUE THREAD

**Issue by yyhran** [tangyuxian/hexo-theme-tangyuxian#6]
文件位置 `.../source/menu/about.md`
生成时候报错如下：
```
INFO  Validating config
INFO  Start processing
INFO  Files loaded in 559 ms
ERROR TypeError: D:\bblog\themes\tangyuxian\layout\post.ejs:2
    1| <div class="nexmoe-post">
 >> 2|     <% if (page.cover){ %>
    3|         <div class="nexmoe-post-cover" style="padding-bottom: <%- page.coverHeight / page.coverWidth * 100 %>%;">
    4|             <img data-src="<%- page.cover %>" data-sizes="auto" alt="<%= page.title %>" class="lazyload">
    5|             <h1><%= page.title %></h1>

Cannot read property 'data' of undefined
    at Object.coverAutoPost (D:\bblog\themes\tangyuxian\scripts\helper\cover_auto_post.js:5:24)
    at eval (D:\bblog\themes\tangyuxian\layout\post.ejs:26:18)
    at post (D:\bblog\node_modules\ejs\lib\ejs.js:682:17)
    at _View._compiled (D:\bblog\node_modules\hexo\lib\theme\view.js:136:50)
    at _View.render (D:\bblog\node_modules\hexo\lib\theme\view.js:39:17)
    at D:\bblog\node_modules\hexo\lib\hexo\index.js:64:21
    at tryCatcher (D:\bblog\node_modules\bluebird\js\release\util.js:16:23)
    at D:\bblog\node_modules\bluebird\js\release\method.js:15:34
    at RouteStream._read (D:\bblog\node_modules\hexo\lib\hexo\router.js:47:5)
    at RouteStream.Readable.read (_stream_readable.js:491:10)
    at resume_ (_stream_readable.js:976:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  path: 'D:\\bblog\\themes\\tangyuxian\\layout\\post.ejs'
}
```
然后会生成一份空的 `about.html` ，无法使用。原 `.md` 文件开头如下：
```
---
title: 关于我
date: 2021/9/15 20:46:25
permalink: about.html
---
```
发现将其放至 `.../source/_posts/about.md` 可以成功生成，但是这样就会在文章归档那里显示出来一份，显得不是太美观(?)，而且好像之前是能成功生成。
本人刚接触 hexo不久 ，查阅相关文档之后没有发现合适的解决方法。

**Comment by tangyuxian** [comment]
请在source文件夹下创建  about.md文件
头部信息修改为

title: 关于
date: 2020-11-07 15:14:00
tags:
layout: about
permalink: about.html
cover: https://cdn.jsdelivr.net/gh/tangyuxian/blog_image@latest/background/xiaomai.jpg
coverWidth: 1200
coverHeight: 520

**Comment by yyhran** [comment]
问题解决，是头部的问题，非常感谢
